import { Recipe } from "@/app/interfaces/recipes";

export const RecipesList: Recipe[] = [
  {
    id: 1,
    image: "/recipes/healthy_koshary.jpg",
    title: "recipes.healthy_koshary.title",
    category: "30 Minutes or Less",
    description: "recipes.healthy_koshary.description",
    foodGroup: ["Grains", "Legumes", "Vegetables"],
  },
  {
    id: 2,
    image: "/recipes/molokhia_with_grilled_chicken.jpg",
    title: "recipes.molokhia_with_grilled_chicken.title",
    category: "30 Minutes or Less",
    description: "recipes.molokhia_with_grilled_chicken.description",
    foodGroup: ["Legumes", "Vegetables"],
  },
  {
    id: 3,
    image: "/recipes/stuffed_zucchini_light.jpg",
    title: "recipes.stuffed_zucchini_light.title",
    category: "30 Minutes or Less",
    description: "recipes.stuffed_zucchini_light.description",
    foodGroup: ["Vegetables", "Grains"],
  },
  {
    id: 4,
    image: "/recipes/bamia_with_olive_oil.jpg",
    title: "recipes.bamia_with_olive_oil.title",
    category: "30 Minutes or Less",
    description: "recipes.bamia_with_olive_oil.description",
    foodGroup: ["Vegetables", "Protein"],
  },
  {
    id: 5,
    image: "/recipes/grilled_fish_with_tahini.jpg",
    title: "recipes.grilled_fish_with_tahini.title",
    category: "30 Minutes or Less",
    description: "recipes.grilled_fish_with_tahini.description",
    foodGroup: ["Protein", "Vegetables"],
  },
  {
    id: 6,
    image: "/recipes/light_lentil_soup.jpg",
    title: "recipes.light_lentil_soup.title",
    category: "30 Minutes or Less",
    description: "recipes.light_lentil_soup.description",
    foodGroup: ["Legumes", "Vegetables"],
  },
  {
    id: 7,
    image: "/recipes/light_potato_tagine.jpg",
    title: "recipes.light_potato_tagine.title",
    category: "30 Minutes or Less, Kid-Friendly",
    description: "recipes.light_potato_tagine.description",
    foodGroup: ["Vegetables", "Protein"],
  },
  {
    id: 8,
    image: "/recipes/diet_grape_leaves.jpg",
    title: "recipes.diet_grape_leaves.title",
    category: "30 Minutes or Less",
    description: "recipes.diet_grape_leaves.description",
    foodGroup: ["Vegetables", "Grains"],
  },
  {
    id: 9,
    image: "/recipes/diet_tuna_salad.jpg",
    title: "recipes.diet_tuna_salad.title",
    category: "30 Minutes or Less, Kid-Friendly",
    description: "recipes.diet_tuna_salad.description",
    foodGroup: ["Protein", "Vegetables"],
  },
  {
    id: 10,
    image: "/recipes/diet_vegetable_omelette.jpg",
    title: "recipes.diet_vegetable_omelette.title",
    category: "30 Minutes or Less",
    description: "recipes.diet_vegetable_omelette.description",
    foodGroup: ["Protein", "Vegetables"],
  },
  {
    id: 11,
    image: "/recipes/diet_baked_potatoes.jpg",
    title: "recipes.diet_baked_potatoes.title",
    category: "30 Minutes or Less",
    description: "recipes.diet_baked_potatoes.description",
    foodGroup: ["Vegetables", "Carbohydrates"],
  },
  {
    id: 12,
    image: "/recipes/diet_banana_oat_smoothie.jpg",
    title: "recipes.diet_banana_oat_smoothie.title",
    category: "30 Minutes or Less",
    description: "recipes.diet_banana_oat_smoothie.description",
    foodGroup: ["Fruits", "Dairy", "Grains"],
  },
  {
    id: 13,
    image: "/recipes/diet_cottage_cheese_avocado_sandwich.jpg",
    title: "recipes.diet_cottage_cheese_avocado_sandwich.title",
    category: "30 Minutes or Less",
    description: "recipes.diet_cottage_cheese_avocado_sandwich.description",
    foodGroup: ["Dairy", "Vegetables", "Grains"],
  },
  {
    id: 14,
    image: "/recipes/diet_yogurt_cucumber_salad.jpg",
    title: "recipes.diet_yogurt_cucumber_salad.title",
    category: "30 Minutes or Less",
    description: "recipes.diet_yogurt_cucumber_salad.description",
    foodGroup: ["Dairy", "Vegetables"],
  },
  {
    id: 15,
    image: "/recipes/diet_grilled_chicken_lemon.jpg",
    title: "recipes.diet_grilled_chicken_lemon.title",
    category: "30 Minutes or Less",
    description: "recipes.diet_grilled_chicken_lemon.description",
    foodGroup: ["Protein", "Vegetables", "Grains"],
  },
];
